### ISSUE TITLE
Unable to deploy to heroku

### ISSUE THREAD

**Issue by spundone** [ShineiIchijo/Chitoge-Guides#2]
The following error appears while trying to deploy the bot

![image](https://user-images.githubusercontent.com/22429346/151708826-bbe72fda-b8e1-4760-8f76-47b0e363b86b.png)

**Comment by LuckyYam** [comment]
Please fork the [Chitoge](https://github.com/ShineiIchijo/Chitoge) and deploy it from the forked repo. Hope you have a great day!
